"""empty message

Revision ID: 1a76f63b721e
Revises: b9ac2ed9319e
Create Date: 2024-01-26 17:09:56.276501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a76f63b721e'
down_revision = 'b9ac2ed9319e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_result', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('quiz_result')

    # ### end Alembic commands ###
