"""empty message

Revision ID: 45bcb0c5e501
Revises: 34e2ced0948c
Create Date: 2024-01-30 15:06:09.014818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bcb0c5e501'
down_revision = '34e2ced0948c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('questions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('attend', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('attend')
        batch_op.drop_column('questions')
        batch_op.drop_column('total')

    # ### end Alembic commands ###
